backend:
  name: git-gateway
  branch: main
media_folder: "images"
public_folder: "uploads"
collections:
- name: "galerie"
  label: "Galerie"
  folder: "/src/_galerie"
  fields:
      - {label: "Image", name: "thumbnail", widget: "image"}