backend:
  name: git-gateway
  branch: main
media_folder: "images"
public_folder: "/"
collections:
  - name: "galerie"
    label: "Galerie"
    folder: "src"
    create: true
    slug: {{slug}}
    fields:
      - {label: "Title", name: "title", widget: "string"}

